.\" Manpage for makever.
.\" Contact simao.nziaka@outlook.com to correct errors or typos.
.TH makever 1 "13 Oct 2019" "v1.0.0" "Makever Manual"

.SH NAME
.B   makever
\- creates a file with more descriptive information based on the version of your package

.SH SYNOPSIS
.B   makever
[-h] [--dry-run] [-c=<codename>] [-o=<file>] [-v=<npm-version-options>] [-m=<tag-message>]
[--std] [--dump] [--tag] [--quiet] [--force]

.SH DESCRIPTION
.B   makever
is a shell program that uses node's package.json version to create a more descriptive version file with a codename.

.SH OPTIONS
.B   makever
takes a few options, as shown here:

\-c, \-\-codename
Set the a codename for the current version

\-o, \-\-output
Set the file to write data to

\-v, \-\-version
[<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease [--preid=<prerelease-id>] | from-git]

\-m
Tag message. Combine with \-\-tag and \-v

\-\-tag
Enable git tagging

\-\-std
Output content on the standard output

\-d, \-\-dump
Dump the current version file to stdout

\-h, \-\-help
Show help

\-q, \-\-quiet
Run without printing to stdout. Shh mode

\-t, \-\-dry\-run
Mock the behaviour of the command wihtout side effects

\-f, \-\-force
Force certain operations to run "dangerously"

\-y, \-\-yes
Directly accept the operation another option is introducing

\-n, \-\-no
Directly deny the operation another option is introducing

.SH MORE DETAILS
1.
.B  makever

makever will generate a version file named "version.json" by default with an auto generated codename.

2.
.B  makever
\-c <codename>

makever will generate a version file named "version.json" by default with a custom codename given by \-c.
Input to \-c must be more than 3 characters.

3.
.B  makever
\-o <file> \-c <codename>

The version file will be created using the filename given by \-o with a custom codename. The extension of the filename can me omitted, it defaults to .json.
\-o can read just the following: 'filename', 'file.json', 'path/to/file', 'path/file.json'.

4.
.B  makever
\-c <codename> \-\-std

Ouput generated data to standard output, wihtout writing to a file. \-\-std cannot be combined with \-o.

5.
.B  makever
\-\-dump

Dumps the contents of the current version file to stdout.

6.
.B makever
\-c <codename> \-v [<newversion> | major | minor | patch | ...]

makever uses the power of npm version under the hood to actually manage your package's version and generate a version file.
So, all the possible options given to npm version can be passed to makever using the \-v or \-\-version options.
And, makever will use it to properly update the version file while npm version does its magic. Additionally, npm version reads
a "prerelease" option, which makever can use to pass a generated codename to, using the '%codename' placeholder.
For example: running ```makever -v "prerelease --preid=%codename"``` for a codename such as "A-stark", the generated pre-release
version would be "v1.0.1-A-stark.0".

7.
.B makever
\-c <codename> \-v patch \-m "Upddate to version %v Codename %c"

Pass a commit message to stamp your new release using the \-m option, use it as you would with npm version.
See: (https://docs.npmjs.com/cli/version).

8.
.B makever
\-c <codename> \-\-tag [\-m "Version %version. Codename %codename"]

\-\-tag allows tagging changes made my makever. For example, when a new codename is generated \-\-tag can be use to create an annotaded tag with the current version and the codename.
Combine \-\-tag with \-m for a tag message. The default tag message for \-\-tag is 'Codename %c'.
\-\-tag will prompt you to accept or deny tagging and pushing the tag. Use \-y or \-n to directly accept or deny the operation.

9.
.B makever
\-c <codename> \-\-quiet

Run makever in Shh mode.

10.
.B makever
[options] \-\-dry\-run

\-\-dry-run can be combined with other options except \-\-dump because an actual version file will not be created.
\-dry\-run runs makever in test mode, it mocks all options and reports their results as if they have actually ran.
Allows the command to be tested and show how it behaves without side effects.

11.
.B makever
\-f, \-\-force

Force runs an operation, it is ignored any time is not relevant.

.SH BUGS
    See: (https://github.com/verdebydesign/makever-cli/issues)

.SH AUTHOR & COPYRIGHT
    (c) 2018-2019 Simao Nziaka (https://simaonziaka.com/)

.SH LICENSE
    ISC License (ISC) (https://opensource.org/licenses/ISC)
