.\" Manpage for makever.
.\" Contact simao.nziaka@outlook.com to correct errors or typos.
.TH makever 1 "24 Aug 2018" "v0.1.0" "Makever Manual"

.SH NAME
.B   makever
\- create a more descriptive file based on the version of your package

.SH SYNOPSIS
.B   makever
[-h] [-c=<codename>] [-o=filename] [-v=npm-version-options] [-m=commit-message]
[--std] [--view] [--no-tag]

.SH DESCRIPTION
.B   makever
is a shell program that uses node's package.json version to create a more descriptive version file accompanying the version with a codename.

.SH OPTIONS
.B   makever
takes a few options, as shown here:

\-c, \-\-codename
Set this version's code name

\-o
The name of the version file.

\-v, \-\-version
[<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease [--preid=<prerelease-id>] | from-git]

\-\-no\-tag
Disable tagging

\-\-std
Output content on the standard output

\-\-view
View the version file content's in the stdout

\-h, \-\-help
Show help

\-m
npm version\'s commit message

.SH MORE DETAILS
1.
.B  makever
\-c <codename>

makever will generate the version file with the default name "version.json".
The file will contain the data about your package's version and it's codename along side some other metadata.

2.
.B  makever
\-o <filename> \-c <codename>

The version file will be created using the filename given \-o. The version file is a json file
but here we can omit the file extension, so both ways <verfilename> and <verfilename.json> work just fine.

3.
.B  makever
\-o <filename> \-c <codename> \-\-std

For any option that actually writes to the version file the \-\-std option can be used to output its data to the stdout
right after the file has been written to.

4.
.B  makever
\-\-view

This option allows you to see the contents of an existing version file.

5.
.B makever
\-c <codename> \-v [<newversion> | major | minor | patch | ...]

makever uses the power of npm version under the hood to actually manage your package's version and generate its version file.
So, all the possible options given to npm version can be passed to makever using the \-v or \-\-version options.
And, makever will use it to properly update the version file while npm version does its magic.

6.
.B makever
\-c <codename> -v patch -m "Upddate to version %s"

Pass a commit message to stamp your new release using the -m option, of course following the -v option
as you would do with npm version. See: (https://docs.npmjs.com/cli/version). Everytime you use the \-v
or \-\-version option always remember to pass the codename before it, as shown above.

7.
.B makever
\-c <codename> --no-tag

All the options that write to the version file, tag the version and the codename on git.
To disable this behavior and take control when tagging happens. use --no-tag

.SH BUGS
    See: (https://github.com/akaizn-junior/makever-cli/issues)

.SH AUTHOR & COPYRIGHT
    (c) 2018 Simao Nziaka (https://simaonziaka.com/)

.SH LICENSE
    ISC License (ISC) (https://opensource.org/licenses/ISC)
